# Generated by Django 5.0.4 on 2024-05-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True, default='https://vk.cc/cx5kFx', null=True),
        ),
    ]
